Vmax: 50          # Vmax [m/s]
rmax: 2.5e4       # radius of Vmax [m] defaults to 25 km
fcor: 5.0e-5      # Coriolis parameter at storm center
Cdvary: false     # whether to vary
C_d: 1.5e-3       # surface momentum.
w_cool: 2.0e-3    # 2 thousandths
CkCdvary: false   # whether to vary
CkCd: 1           # ratio between ck and cd
eye_adj: false    # whether to adjust eye
alpha_eye: 0.15   # v/vm reduced by a factor (r/rm) in eye
