angle:
  min: -90.0
  max: 90.0
  units: degree
speed:
  min: 2
  max: 20
  units: m s**-1
point_east:
  min: -0.6
  max: 1.2
  units: "degrees east"
rmax:
  min: 2000
  max: 60000
  units: "meters"
pc:
  min: 90000
  max: 98000
  units: "Pascal"
xn:
  min: 0.8
  max: 1.4
  units: "Dimensionless"
