"""Generate hurricane."""
import os
from typing import Tuple
import numpy as np
import matplotlib.pyplot as plt
import climada.hazard.trop_cyclone as tc
from src.constants import FIGURE_PATH, NO_BBOX
from sithom.plot import plot_defaults, label_subplots
from src.data_loading.ibtracs import katrina, prep_for_climada

MODEL_VANG = {"H08": 0, "H1980": 1, "H10": 2}


def make_katrina_windfields(model: str = "H08") -> Tuple[np.ndarray]:
    """
    Make Katrina Windfields for input.

    Args:
        model (str): e.g. "H08"

    Returns:
        Tuple[np.ndarray]: The tuple of outputs (output, nodes)
    """
    centroids = np.array(
        [
            [x, y]
            for x in np.linspace(*NO_BBOX.lat, num=50)
            for y in np.linspace(*NO_BBOX.lon, num=50)
        ]
    )
    return tc.compute_windfields(
        prep_for_climada(katrina()),
        centroids,
        tc.MODEL_VANG[model],  # metric="equirect"
    )


def plot_katrina_windfield_example(model="H08") -> None:
    """
    Plot the Katrina windfield that would
    be generated by `climada` using the Holland Hurricane Model.

    Args:
        model (str, optional): Model output. Defaults to "H08".
    """
    plot_defaults()
    output = make_katrina_windfields(model=model)
    _, axs = plt.subplots(2, 1, sharex=True)
    axs[0].plot(output[0][50, :, 0])
    axs[0].set_ylabel("x-wind [m s-1]")
    axs[1].plot(output[0][50, :, 1])
    axs[1].set_ylabel("y-wind [m s-1]")
    axs[1].set_xlabel("Node")
    label_subplots(axs)
    plt.savefig(os.path.join(FIGURE_PATH, "katrina-" + model + "-windfields.png"))
    plt.clf()


if __name__ == "__main__":
    for key in tc.MODEL_VANG:
        plot_katrina_windfield_example(model=key)
    # plot_katrina_windfield_example(model="H08")
    # python src/models/generate-hurricane.py
